name: pull-request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  call-workflow:
    uses: mario-backstage-demo/shared-workflows/.github/workflows/quarkus-ci.yaml@main
    with:
      app: ${{values.application.split(":")[1]}}